[package]
name = "paradox-backup"
version = "0.1.0"
authors = ["Bastien Jacot-Guillarmod <bjacotg@gmail.com>"]
edition = "2018"

[dependencies]
notify = "4.0.0"
clap = "2.32.0"
regex = "1"
log = "0.4" 
env_logger = "0.6.0"
chrono = "0.4"
